apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-ingress
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: ingress/
    repoURL: https://github.com/nnabueze/appKustomiseDeployManifest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true