apiVersion: v1
kind: Service
metadata:
  labels:
    app: math-app
  name: service-preview
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: math-app
  type: ClusterIP
